server:
  port: 8080
  connection:
    client:
      max_connection_idle_time_ms: 200000
    origin:
      connect_timeout_ms: 1000
      read_timeout_ms: 2000
      connection_pool_size: 101
      max_read_buf_size_kb: 32
log:
  level: 2
  path: "/var/log/hitori.log"
  max_age: 7
  cut_duration_min: 1440
  cut_size_mb: 100
mapping:
  domains:
    -
      domain_name: "example.com"
      origins: "default"
      cache_config:
        enable: true
  origin_sources:
    -
      origin_name: "default"
      protocol: "http"
      nodes:
        - "http://127.0.0.1:8000"
cache:
  enabled: true
  slice_size_kb: 1024
  expiration_time_second: 3600
  disk:
    devices:
      -
        path: "/var/cache/proxy"
        size_mb: 500